site:
    resource: '@SiteBundle/Resources/config/routing.yml'
    prefix: /

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"
genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"
genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"

smart_core_cms:
    resource: "@CMSBundle/Resources/config/routing.yml"
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /%user_path%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /%user_path%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /%user_path%/register

fos_user_resetting:
    resource: "@CMSBundle/Resources/config/routing/fosuser_resetting.xml"
    prefix: /%user_path%/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /%user_path%
